# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\arayuz\info_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Info_2(object):
    def setupUi(self, Info_2):
        Info_2.setObjectName("Info_2")
        Info_2.resize(800, 600)
        Info_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(Info_2)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 60, 501, 71))
        self.label.setStyleSheet("font: 20pt \"MS Gothic\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 210, 501, 71))
        self.label_3.setStyleSheet("\n"
"font: 12pt \"MS Gothic\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 290, 501, 71))
        self.label_4.setStyleSheet("font: 12pt \"MS Gothic\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 370, 501, 71))
        self.label_5.setStyleSheet("font: 12pt \"MS Gothic\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(580, 50, 121, 171))
        self.label_2.setStyleSheet("border-image: url(:/resim/b.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        Info_2.setCentralWidget(self.centralwidget)

        self.retranslateUi(Info_2)
        QtCore.QMetaObject.connectSlotsByName(Info_2)

    def retranslateUi(self, Info_2):
        _translate = QtCore.QCoreApplication.translate
        Info_2.setWindowTitle(_translate("Info_2", "MainWindow"))
        self.label.setText(_translate("Info_2", "Dr. Instructor Mehmet Erdal ÖZBEK"))
        self.label_3.setText(_translate("Info_2", "Extension Number:  3811"))
        self.label_4.setText(_translate("Info_2", "E-Mail : merdal.ozbek@ikcu.edu.tr"))
        self.label_5.setText(_translate("Info_2", "Office Information:  Central Offices-1   Room Number: "))
import resims_rc
