# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\arayuz\info_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_info_1(object):
    def setupUi(self, info_1):
        info_1.setObjectName("info_1")
        info_1.resize(793, 521)
        info_1.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(info_1)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 60, 501, 71))
        self.label.setStyleSheet("font: 20pt \"MS Gothic\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(570, 50, 121, 171))
        self.label_2.setStyleSheet("border-image: url(:/resim/a.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 210, 501, 71))
        self.label_3.setStyleSheet("\n"
"font: 12pt \"MS Gothic\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 290, 501, 71))
        self.label_4.setStyleSheet("font: 12pt \"MS Gothic\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 380, 501, 71))
        self.label_5.setStyleSheet("font: 12pt \"MS Gothic\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        info_1.setCentralWidget(self.centralwidget)

        self.retranslateUi(info_1)
        QtCore.QMetaObject.connectSlotsByName(info_1)

    def retranslateUi(self, info_1):
        _translate = QtCore.QCoreApplication.translate
        info_1.setWindowTitle(_translate("info_1", "MainWindow"))
        self.label.setText(_translate("info_1", "Assist. Prof.Dr. Esra AYCAN BEYAZIT"))
        self.label_3.setText(_translate("info_1", "Extension Number:  3758"))
        self.label_4.setText(_translate("info_1", "E-Mail : esra.aycan@ikcu.edu.tr"))
        self.label_5.setText(_translate("info_1", "Office Information:  Central Offices-1   Room Number: 141"))
import resims_rc
